item:
  type: diamond sword     # <type|material>
  amount: 1               # (amount)
  name: custom name       # (name)
  lore: [monkey, mono]    # (lore)
  custom-model: 10001     # (custom-model)
  damage: 100             # (damage|durability)
  repair-cost: 100        # (repair-cost)
  flags: [ hide enchants ]
  unbreakable: false      # (unbreakable)
  enchants:               # (enchants|enchantments)
    sharpness: 5
  attributes:             # (attributes)

    - type: generic.attack_damage    # <type|attribute>
      name: Attack Damage Modifier   # (name)
      amount: 2.0                    # <amount>
      slot: mainhand                 # <slot>
      operation: 0                   # <operation>

   # You can also use nested sections ->
   #attack_speed:
   #  type: generic.attack_speed
   #  name: Attack Speed Modifier
   #  amount: 2.0
   #  slot: mainhand
   #  operation: 0

location:
  world: world   # (world)
  x: 100         # <x>
  y: 100         # <y>
  z: 100         # <z>
  yaw: 10        # (yaw)
  pitch: 10      # (pitch)

locations:
  - { world: world, x: 100, y: 100, z: 100, yaw: 10, pitch: 10 }
  - { x: 100, y: 100, z: 100, yaw: 10, pitch: 10 }
  - { world: world, x: 100, y: 100, z: 100 }
  - { x: 100, y: 100, z: 100 }






